### ISSUE TITLE
Synchronize README with Wiki / Manual

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#1]
The README still is called 'admin_gui_gen', rename to correct project name.
Include a remark that only required information is read from the input JSON files and that thus the same files can be used for generating the graphql-server and the single-page-app as well.

### Expected work time: 30 minutes

**Comment by vsuaste** [comment]
Done. [#5b8a42](https://github.com/ScienceDb/single-page-app-codegen/commit/5b8a42bd7ecdd3a7fa186222b65d2b809d7aafe1#diff-04c6e90faac2675aa89e2176d2eec7d8), [#2e1672](https://github.com/ScienceDb/single-page-app-codegen/commit/2e1672d713e1ee88569c7fa91883d4940242a8d9#diff-04c6e90faac2675aa89e2176d2eec7d8)
