### ISSUE TITLE
Fix missing validation error display in writing (create/update) operations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#11]
The old RESTful application successfully displayed validation error messages. 
The related component is 

* displaying and storing the error [`views/pages/formElements.ejs`](https://github.com/ScienceDb/single-page-app-codegen/blob/master/views/pages/formElements.ejs) (lines 12 to 14 and 132 to 137)
* setting the error messages after 
  * create [`views/pages/createForm.ejs`](https://github.com/ScienceDb/single-page-app-codegen/blob/master/views/pages/createForm.ejs) lines 42 to 52
  * update [`views/pages/editForm.ejs`](https://github.com/ScienceDb/single-page-app-codegen/blob/master/views/pages/editForm.ejs) lines 61 to 70

To fix the display you just have to extract the error messages correctly and set them in the respective components. How this has to be done can be seen in the above components. It might be helpful to run in an interactive node environment the creation of a record and intentionally cause a validation error to be able to inspect its structure. 
For example start `node` in a sandbox test graphql-server with some playground models. Then `var models = require('src/models/index.js')`. Then `models.book.create( {name: 124} )`, ensure that in book there is a string validation. Now you should see a validation error and can inspect its structure.

Based on the above you can write an integration test.

#### IMPORTANT: Global error

The above components can display global errors, if the validation error is not associated with a certain attribute, or if another unexpected error occurs. To display that, please use the component implemented in [this Issue of `single page application`](https://github.com/ScienceDb/single-page-app/issues/1).

### Expected work time: 2d

**Comment by vsuaste** [comment]
Done.  Commits [#96d4bb](https://github.com/ScienceDb/single-page-app-codegen/commit/96d4bb343fcb065222362ee5d5ee0f93ba5b2360) [#f09164](https://github.com/ScienceDb/single-page-app-codegen/commit/f091640083589af653808c481feb9cefa2329392) [#7ca107](https://github.com/ScienceDb/single-page-app-codegen/commit/7ca107091471fb3ccb5152ccaecdadbf9fd96a1e) [#eaa01e](https://github.com/ScienceDb/single-page-app-codegen/commit/eaa01e75670a63906764ea8559fb2b4b5d1d8c0f)
