### ISSUE TITLE
Usage should be the same for 'graphql-server-model-codegen' and 'single-page-app-codegen'

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#13]
Trying out our tool-set one realizes that to generate the graphql-server one executes:
```
index.js generate ../data_model_definitions .
```
while to generate the single page application one executes:
```
index.js --jsonFiles ../data_model_definitions .
```

Two points:
1) The argument `generate` to the above server code generators does not make any sense as it is the _only_ function implemented by the code generator anyway.
2) The argument `--jsonFiles` is required to generate the single page application but will not be accepted by the graphql-server generator. This causes our toolset to appear quite immature.

Please decide on a single usage and implement it in both tools.

_Be mindful_ that this effects the integration tests and possible other automated calls to our tools.

### Expected work time: 3h

**Comment by vsuaste** [comment]
Done. Commits: [#2c17c6](https://github.com/ScienceDb/single-page-app-codegen/commit/2c17c683a8aec3e0e2566ec90119960afacf2315) [#2c17c6](https://github.com/ScienceDb/single-page-app-codegen/commit/2c17c683a8aec3e0e2566ec90119960afacf2315) [#e55356](https://github.com/ScienceDb/ScienceDb.github.io/commit/e55356b79e28dc6090036d7df021d7886284529a)
