### ISSUE TITLE
Urgent: Fix naming of generated functions, especially resolvers

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#15]
When using model names, e.g. with CamelCase the functions generated for the single-page-application do not match the `resolvers` generated for the `graphql-server`. 

This Issue thus involves both code generators:
- [`single-page-app-codegen`](https://github.com/ScienceDb/single-page-app-codegen)
- [`graphql-server-model-codegen`](https://github.com/ScienceDb/graphql-server-model-codegen)

Please evaluate whether the following very simple approach does not solve our lamentably re-occurring problems with changing cases and using pluralized model names:
Simply leave the model name as it is in the original model definition (input.json) and just put the respective pre- and post-fixes as needed. **_We need to solve this Issue once and for all, please!_**

Write extensive unit and integration tests for lower-case, capital-case, CamelCase, snake_case, kebap-case model names. Include attribute names of the same casing. If necessary we can agree on the requirement that model names _must_ only be using snake_case or something similar. However, it does not seem a necessary requirement. 

### Expected work time: 2d

**Comment by vsuaste** [comment]
Done. Commits [#6db55b](https://github.com/ScienceDb/single-page-app-codegen/commit/6db55b811d7b341b872f9aee2eb249125f1b61ca) [#fc84c2](https://github.com/ScienceDb/single-page-app-codegen/commit/fc84c270d30fd9b0cedb4deff5ae03b8d1887b94) [#98cb60](https://github.com/ScienceDb/single-page-app-codegen/commit/98cb6023423703652408c78700f644598108e236) [#51e9c8](https://github.com/ScienceDb/single-page-app-codegen/commit/51e9c87d6325764dcb04dbe701f47b636007f53e) [#ed4c0fd](https://github.com/ScienceDb/single-page-app-codegen/commit/ed4c0fd8bc446f3663e56742a43e395d932016b1) [#df9435](https://github.com/ScienceDb/single-page-app-codegen/commit/df9435c47aac853bb154cfed1c649e2e4e618968)

### Actual work time 3d
