### ISSUE TITLE
When using default data model definitions for user and role the hasMany relationships are not displayed

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#16]
Assume the two default models `role` and `user`
```
{
  "model" : "user",
  "storageType" : "SQL",
  "attributes" : {
    "email" : "String",
    "password" : "String"
  },
  "associations" :{
    "roles" : {
      "type" : "sql_belongsToMany",
      "target" : "role",
      "targetKey" : "roleId",
      "sourceKey" : "userId",
      "keysIn" : "role_to_user",
      "targetStorageType" : "sql"
    }
  }
}
```
```
{
  "model" : "role",
  "storageType" : "SQL",
  "attributes" : {
    "name" : "String",
    "description" : "String"
  },
  "associations" : {
    "users" : {
      "type" : "sql_belongsToMany",
      "target" : "user",
      "targetKey" : "userId",
      "sourceKey" : "roleId",
      "keysIn" : "role_to_user",
      "targetStorageType" : "sql"
    }
  }
}
```

Using `single-page-app-codegen` results in components being created that are _not_ capable of displaying the relationships between a user and his roles. The displayed relationship-list shows the expected three elements created by the project's seeders, but each list entry remains empty in the detail-row and the edit components of user. No error gets reported, not in the log and also not in the Browser's (Chrome) Console or Network.

Before anything else write an integration test that reproduces this error. Afterwards fix it. Ask @YKolokoltsev for details on how to write such an integration test.

### Expected work time: 1d

**Comment by asishallab** [comment]
### IMPORTANT UPDATE: Found the cause of the error

The cause of the error were missing `label` and `sublabel` arguments in the respective model definitions. 

Make the code generator raise an error in case `label` for relationships is _not_ given. Make it an required argument. 

### Expected work time: 3h

**Comment by vsuaste** [comment]
Done. [#d04044](https://github.com/ScienceDb/single-page-app-codegen/commit/d0404413be21a77c8ec7ead51db17b14f7a141a2)
