### ISSUE TITLE
Vuetify

### ISSUE THREAD

**Issue by vsuaste** [ScienceDb/single-page-app-codegen#17]
Research and design the change of the SPA for using Vuetify.
In each one of the component identify the elements that should be changed and write it down.
Read: [Vuetify](https://vuetifyjs.com/en/)

**Comment by asishallab** [comment]
Please keep the following topics in mind, when planning the design of the new Vuetify based SPA:

* Authorization (ACL): Do we ask the graphql-server if a logged in user has the right to see / use a component, or do we use a different approach?
* Internationalization: How to display messages / text in different languages? See [this Vuetify document](https://vuetifyjs.com/en/framework/internationalization)

**Comment by asishallab** [comment]
For the code generator input.json files consider also an extension, as given in the following example `dog.js`:
```
{
  "model": "Dog",
  "storageType": "Sql",
  "attributes": {
    "name": {
      "type": "String",
      "spa_component": {
         "type": "text-field"
      }
    },
    "description": {
      "type": "String",
      "spa_component": {
         "type": "rich-text-editor"
      }
    },
    "birthDate": {
      "type": "String",
      "spa_component": {
         "type": "date-selector",
         "date-format": "dd/mm/yyyy"
      }
    }
  }
}
```

The above should _not_ obsolete the "old" current option to just define the attributes like this:
```
  "name": "String"
```
Rather it should be an extension ("new") to give the code generators more details on the attributes, particularly on what components to use in the single page application. As seen in the above `date-selector` example, additional information like `date-format` can be given.

#### Important note: Please assess how difficult it would be to offer _both_ the "old" and "new" way to define attributes

If too difficult to offer both modes of attribute definitions, then just use the "new" one.

**Comment by asishallab** [comment]
We opted for material-ui with React
