### ISSUE TITLE
Make integration-tests more agile

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#21]
To understand this Issue in more depth, please consult [this white paper](https://docs.google.com/document/d/1twnXUrdi8G-mXzNycdnAlx0ZvGNxcd9rMVsofnSEt4M/edit?usp=sharing) on the motivation and design changes planned for the integration-test-suite.

Basically, this Issue is the equivalent of the graphql-server-code-generator [Issue #67](https://github.com/ScienceDb/graphql-server-model-codegen/issues/67) for the single page application code generator.

Please follow as closely as possible the instructions in the above Issue #67.

Key difference here is, that the generated single page application does not need to be restarted, when the code-base is changed, as it should be served in development mode. In this development mode, the server detects changes in the components and re-compiles them, so the changes are directly applied.

**Comment by framirez07** [comment]
The required functionality was implemented. Please check branch i21.
