### ISSUE TITLE
Experiment: Estimate work load for switching either to material-ui or vuetify

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#23]
Implement the table component that displays a subset of records for a single data model in both [material-ui](https://material-ui.com/components/tables/#tables) and [Vuetify](https://vuetifyjs.com/en/components/data-tables). 

* Keep log of the time spent and especially problems encountered.
* Do not spend more than max three days per framework. If you do not finish in that time, that is a result, too.
* Aim at reusing the API Node.JS files generated for the SPA by our code-generator for each model. In these files you find functions that ease the interaction with the GraphQL-Server. Ask @vsuaste for details, if any doubts.

Functions that should be implemented in these two React and Vue components:
* Sort by column
* Paginate 
* Simple search (as implemented now)

**Comment by framirez07** [comment]
HI!

### TableView - Vuetify: Done
The table component was implemented for Vuetify.

All requested functionality is implemented:
- Sort by column
- Paginate
- Simple search (as implemented now)

### Branch:
[**i23-spa-codegen-vuetify**](https://github.com/ScienceDb/single-page-app-codegen/tree/i23-spa-codegen-vuetify)

### How to test
Can be tested with StarterPack  doing additional following steps:

After submodules initialization phase:
`$ cd single-page-app`
`$ git checkout spa-vuetify`

Before install code generators, change the branch on `Dockerfile.code-generators` as follows:
`npm install -g github:ScienceDb/single-page-app-codegen.git#23-spa-codegen-vuetify`

### Next step
TableView - React.


Regards!

**Comment by framirez07** [comment]
HI!

### TableView - Material-UI (React): Done
The table component was implemented for React.

All requested functionality is implemented:
- Sort by column
- Paginate
- Simple search (as implemented now)

Except:
- EJS templates.
- Virtual-lists on detail row view.
- Floating buttons for add, export and import actions.

### Branch:
[**spa-react**](https://github.com/ScienceDb/single-page-app/tree/spa-react)

### How to test
Can be tested with StarterPack doing additional following steps:

After submodules initialization phase:
`$ cd single-page-app`
`$ git checkout spa-react`

After generate code, copy/replace following files:
`$ cd single-page-app/src`
`$ cp i23/roles.vue components/`
`$ cp i23/RoleDetailRow.js components/`
`$ cp i23/role.js requests/`

**Comment by asishallab** [comment]
This Issue has been resolved.
Cenzontle's SPA will be re-implemented using material-ui components.

For the resulting definitions see [this white-paper](https://docs.google.com/document/d/1rxjcQ2zrsI9Edz3_34EEL7ja6lhbaoRRwDb9ywLQ4UE/edit?usp=sharing)
