### ISSUE TITLE
Sketch the design of the new material design based graphical interface (SPA)

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#25]
### Design the new graphical browser based interface

- Use material design (Vuetify or Material-UI).
- Use state management (login, logout, maybe even for errors and warnings)
- Think of authorization, i.e. the user will be delivered inside a token including his roles. Based on these roles decide whether the signed in user has access to a certain component. 

#### Components

In the following we describe the components that need to be developed. 

* `Login`: Sign in user
* `Menu`: Allow navigation depending on existing list of data models. Check to which data models a user has read access. Include item to GraphiQL interface (check rights).
* `MessageComponent`: Display general messages, warnings, and errors on top of page.
* `Table-View`: List subset of records paginated. Simple search, column sort, add-button, example-csv button, upload csv button (bulk-create). 
* `Row-Component`: Can be part of the above Table-View. Used in the above: Has buttons for edit and delete. 
* `Detail-View`: Show (read access) the details of a record. Allow (maybe tab) to see associations. Decide whether associations are displayed using the Table-View of the respective associated records.
* `Edit-View`: Allow to edit the record (check rights). Show specific errors (validation).
* `Create-View`: Like above Edit
* `Delete-Button`: Can be included in Table-View. Must be confirmed.
* `AssociationComponent`: Selects either the DetailView or the TableView of the respecively associated records depending on if the association is to-one or to-many.

Add components, that are also needed. Prepare a sketch in a Google Drawing or on paper to give a rough overview of the new interface. Also specify which existing material design component will be used for the above and what are the required properties (input), functions, and data formats. Basically, provide a rough sketch of how this could be implemented.

The components can be planned in [this white paper](https://docs.google.com/document/d/1rxjcQ2zrsI9Edz3_34EEL7ja6lhbaoRRwDb9ywLQ4UE/edit?usp=sharing).

**Comment by framirez07** [comment]
Hi!
Scketches added on white paper.
