### ISSUE TITLE
Add SHORT explaining text to Add and Remove when managing associations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#32]
A little subtext should be added that explains the newby user of how to work with the interface.

Add: "Please select the records that you want to be associated with this 'User'" 

Remove: "Please select the records that you no longer want to be associated with this 'User'"

Obviously in the above examples 'User' should be replaced by the data model's name. Do this only if our I18n module allows for such constants. Otherwise use AddExplainTextHead + dataModelName + AddExplainTextTail....

**Comment by framirez07** [comment]
Explaining text added.
Done on this: [commit](https://github.com/ScienceDb/single-page-app-codegen/commit/d819e1b251cfde4ab6d33b3536cbb7f4dd059673)
