### ISSUE TITLE
Show the Edit and Delete Buttons in the Detail View 

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#33]
The respective Edit and Delete Icons should appear in the top bar of the detail view of a record.

Special behavior:

In case the delete button put the delete view on top of it, and
* if the record is actually deleted, close both, or
* if the user hits "cancel deletion" only close the delete view.

In case the User select edit from the detail view, close the detail view and open the edit view.

**Comment by framirez07** [comment]
Edit and Delete buttons was added on Detail-View with the functionality mentioned above.
Please see: [commit](https://github.com/ScienceDb/single-page-app-codegen/commit/155b499b7b809f679dd4062218104c8c1f3cea75).

Additional support is needed to refresh the updated/deleted item in a Detail-View when its needed, for this, the issue #35 was opened.
