### ISSUE TITLE
Add "download CSV template" to table view 

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#34]
Add a little Icon (Button) that allows to download the example table (CSV).

**Comment by framirez07** [comment]
Required functionality implemented.

Commits: [spa](https://github.com/ScienceDb/single-page-app/commit/3b3cb938b343d7045466252911d8b57e8ddf024a) & [spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/98d819679ee28f3cfcb5cabdc7716ef5a851206b)
