### ISSUE TITLE
Alter texts and icons in Component that manages to-many associations

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#36]
Please implement some minor changes.

The changes requested are explained in [this slide](https://docs.google.com/presentation/d/1Qq3rbq16BwQ7Onq4GDYQLaBSIxqeMwC4vKFU-X_4MLw/edit?usp=sharing).

**Summary:**

* The red plus icons in the "Associated" box shall be replaced with red minus signs
* The text shown in the "To Add" box when no records have been selected yet, shall be "No records marked for association"
* The text shown in the "To Remove" box when no records have been selected yet, shall be "No records marked for dis-association".

#### Expected work time: 2 hours

**Comment by framirez07** [comment]
Changes implemented.

Commits:
[spa](https://github.com/ScienceDb/single-page-app/commit/02b145d97f3ec393bd7f497ddd5313a81adaef73)
[spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/d95dd70707fad50c212746b9e826cb25455ba53c)
