### ISSUE TITLE
After clicking "create", "update", "delete" buttons disable them temporarily

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#38]
All buttons in the single-page-application that actually cause data changing requests to be sent to the graphql-server should be disabled upon the first click, until a response is received by the server. See the material-ui API for [button](https://material-ui.com/api/button/) on how to do this.

Check the SPA thoroughly to do that for _all_ data changing buttons or any other trigger (links etc).

**Comment by framirez07** [comment]
**Changes:**

- Debounce and event contention support added on:

> `modified:   views/pages/model-table/components/model-create-panel/ModelCreatePanel.ejs`


- `utils.ejs` file added, which contains `makeCancelable` function to equip promises with `cancel()`, useful to handle the returns of a promise when the parent component is already unmounted:

> `modified:   index.`
> `new file:   views/pages/utils/utils.`

**Commits:**
[spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/1669ec43a872498e9b7fad999642ee71bd59c985)

**Comment by framirez07** [comment]
Changes:

Debounce added on:

> modified: views/pages/model-table/components/model-update-panel/**ModelUpdatePanel.ejs**

**Coomits:**
[spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/73ed66ad69521789e620813743838c96d14e7e78)

**Comment by framirez07** [comment]
Changes:

Debounce added on:

> MainPanel.js

**Commits**
[spa](https://github.com/ScienceDb/single-page-app/commit/78cb2eec4a7d1ccd67a42fae8c461f1c0483ff50)

**Comment by framirez07** [comment]
Debounce and event contention added on all components that needs it:

```
modified:   views/pages/model-table/components/ModelDeleteConfirmationDialog.ejs
modified:   views/pages/model-table/components/ModelEnhancedTableToolbar.ejs
modified:   views/pages/model-table/components/ModelUploadFileDialog.ejs
modified:   views/pages/model-table/components/model-create-panel/ModelCreatePanel.ejs
modified:   views/pages/model-table/components/model-create-panel/components/model-associations-page/ModelAssociationsPage.ejs
modified:   views/pages/model-table/components/model-detail-panel/ModelDetailPanel.ejs
modified:   views/pages/model-table/components/model-update-panel/ModelUpdatePanel.ejs
modified:   views/pages/model-table/components/model-update-panel/components/model-associations-page/ModelAssociationsPage.ejs
```
Commits:
[spa-codegen](https://github.com/ScienceDb/single-page-app-codegen/commit/0c8195c4f529ebbc88e760125368ff9c4c967dc5)
