### ISSUE TITLE
Create a dockerized test server which can be used for integration tests

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#4]
Prepare a set of three docker containers that enable to execute integration tests on a running real life installation of Science DB with test data. The following three docker containers need to be up and running:
- A relational database server: Postgres
- The GraphQL web server
- The Vue JS single page application can either be run in development mode inside a third server or be compiled to be served statically from the GraphQL container.

Create a new Git branch "dockerize" and copy the necessary files from graphql-server-model-codegen into equally named folders in this project. Consider especially the following directories:
- [`./docker`](https://github.com/ScienceDb/graphql-server-model-codegen/tree/master/docker)
- [`./test`](https://github.com/ScienceDb/graphql-server-model-codegen/tree/master/test), and the file
- [`package.json`](https://github.com/ScienceDb/graphql-server-model-codegen/blob/master/package.json) where the commando `npm run test-integration` is defined

As always adhere strictly to our coding guidelines and the efficiency mantras.

### Expected work time: 16 h (two work days)

Sound an alarm if after half the expected work time finishing the issue within the expected time does not seem realistic any more.

**Comment by YKolokoltsev** [comment]
Was closed for a long time ago.
