### ISSUE TITLE
Enable the table-component to work with cursor based pagination

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#40]
In distributed data models, cursor based pagination is the _only_ solution for pagination as it permits to paginate through data without having to fetch _all_ records to enable correct sorting and subsequent correct sub-setting (batching).

Extend the functionality of the table-component to work with cursor based pagination and data delivered in the GraphQL connection format (graphql.org/learn/pagination/#complete-connection-model). Ask @vsuaste for details on the respective GraphQL queries that implement cursor based pagination and that are generated for each data model.

If helpful, extend the data model specific modules in the generated single page application to include a function that handles querying the above cursor based pagination GraphQL queries implemented in the respective GraphQL-server.

Cursor based pagination will affect the pagination component below the table, because it does not allow to jump to a specific page, as the number of pages is unknown. So only offer forward and back buttons. These button should only be active (or visible), if the returned connection object includes a non-null back and next-cursor. 

The cursor based pagination _must_ always be used in table component when generated for distributed data models. 

Implement cursor based pagination support in the table-component in such a way that switching from limit-offset-pagination to cursor-based one becomes extremely easy, possibly provide a property named `pagination-type`, that by default is `limit-offset`, but in the case of distributed data-models is set to `cursor-based`. If this "property" is not trivial to implement, provide immediate feedback before starting this issue. 

### Expected work time: 2 days

**Comment by framirez07** [comment]
Completed.
