### ISSUE TITLE
Support "extended identifiers" in the single page application's components

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#41]
"Extended identifiers", are IDs that are not hat are not necessarily named `id` and are not necessarily of the data type integer. They can have any name, e.g. `URI`, and can be any of the following three data-types: `string`, `integer`, and `float`. - Although `float` is _not_ recommended due to assignment and uniqueness problems that can arise from rounding. - The backend `graphql-server` already supports these custom or "extended identifiers". 

Extend the front-end single page application to be able to handle the above explained custom identifiers. Ask @vsuaste and @coeit for details on how such custom identifiers are defined in our data-model,json files. 

Consider writing, or generating, helper functions in the respective data-model modules, if repetitive code is required. 

### Expected work time: Two to three days

**Comment by framirez07** [comment]
Completed.
