### ISSUE TITLE
Throw an error if limit-offset pagination is requested for non-SQL data models

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#45]
Currently we offer two types of pagination:
 
* limit-offset, and
* cursor-based (Connection)
 
However, limit-offset based pagination can only be supported by certain storage technologies. Especially distributed data models cannot support it, but must be used with `cursorBased` pagination. Please make sure the code generator throws an error, if in the respective data model definition the user requests `limit-offset` based pagination which is not supported.

### Expected work time: 1h

**Comment by framirez07** [comment]
Completed on this commit:
[i45 & i46 - Throw error on nonSql&limitOffset combination - paginatio…](https://github.com/ScienceDb/single-page-app-codegen/commit/3751e4a29b2f88bc5ccf843a0c2f52fa5f1a63cb)
