### ISSUE TITLE
Make cursor based pagination the default

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#46]
We offer support for two pagination methods
* cursor based, and
* limit-offset based.

The advantage of limit-offset based pagination is that the user can directly jump to a specific page, identified by its number. However, cursor based pagination is very much more efficient. The reason is that the storage needs to sort all records and skip through the long list until it reaches the desired offset. No indexing or other method helps here. On the other hand cursor based pagination enables the usage of database indices and starts counting on the provided cursor, thus it is potentially more resource efficient. Another reason is that some storage types only support cursor based pagination. Hence using this as default will make the interface feel more homogeneous and standardized. 

So, make "cursor-based-pagination" the default.

### Expected work time: 1h

**Comment by framirez07** [comment]
Completed on this commit:
[i45 & i46 - Throw error on nonSql&limitOffset combination - paginatio…](https://github.com/ScienceDb/single-page-app-codegen/commit/3751e4a29b2f88bc5ccf843a0c2f52fa5f1a63cb)
