### ISSUE TITLE
Fix 'missing python' during creation of the 'science_db_graphql_server' image when installing the npm bcryptjs package

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#7]
There is an error occurring when building the Docker image of the GraphQL web-server.

See [this Dockerfile](https://github.com/ScienceDb/single-page-app-codegen/blob/master/docker/Dockerfile.graphql_server) and especially [this _resolving_ commit](https://github.com/ScienceDb/graphql-server-model-codegen/commit/ce41df97a127b7e0e282cf65cc10f8918bd8becf) in [graphql-server-model-codegen](https://github.com/ScienceDb/graphql-server-model-codegen) for more details.

Apply the same fix as has been done in the above commit. 

#### _Note_ that you must delete the respective docker image every time before testing whether you can generate the bug and whether your applied fix solves the bug. 

Identify the docker image `ID` with `docker images | grep science_db_graphql_server` and then delete the image manually with `docker rmi -f <your_image_id>`.

**Comment by YKolokoltsev** [comment]
Already fixed in master, closing.
