### ISSUE TITLE
"Network request failed" after some time (expiration problem?)

### ISSUE THREAD

**Issue by asishallab** [ScienceDb/single-page-app-codegen#86]
When testing our test site at http://spa.zendro-dev.org/ the error occurred.

This is a possible bug. After signing in the site works as expected and well. However, after some time of inactivity, when coming back to the site the error is shown. Does it mean my token expired? If so the error message is confusing and the user ideally should be lead back to the login page on which the message: Your session has expired, please sign in again, is shown. 

![image](https://user-images.githubusercontent.com/575529/117115164-0a50e600-ad8d-11eb-84a8-3cfc07cae4b7.png)

**Comment by davelsio** [comment]
Fixed in [single-page-app#67](https://github.com/Zendro-dev/single-page-app/pull/67).
